### ISSUE TITLE
当我在构建配置cmake时候出现错误，不知道该怎么办啊~

### ISSUE THREAD

**Issue by fluenceIR** [cqmoe/cqcppsdk-docs#1]
```
[CMake]   Unknown CMake command "cq_add_std_app".
[CMake] 
[CMake] 
[CMake] -- Configuring incomplete, errors occurred!
```
https://cqcppsdk.cqp.moe/guide/getting-started.html#%E6%9E%84%E5%BB%BA
就是这一步我运行错误。。不知道该怎么办了。
QQ:343762602

**Comment by stdrc** [comment]
现在再重新下载模板和 SDK 试试呢，我不太确定是不是有个提交没有推送，刚刚推送了

如果还不行的话，发一下你的 `CMakeLists.txt` 和 `extern/cqcppsdk/cqcppsdk.cmake` 看看

**Comment by fluenceIR** [comment]
刚刚重新试了一下，可以了，谢谢啦，初学者，麻烦你了~
